export const LAUNCH_APP = "launch_app";
export const SET_PROFESSION = "SET_PROFESSION";
export const SHOULD_SEE_BEHIND = "SHOULD_SEE_BEHIND";
export const SETIDCENTRE = "SETIDCENTRE";
export const MY_FICHES = "MY_FICHES";

export const GET_APP_SPECIALTIES_REQUEST = "GET_APP_SPECIALTIES_REQUEST"
export const GET_APP_SPECIALTIES_SUCCESS = "GET_APP_SPECIALTIES_SUCCESS"
export const GET_APP_SPECIALTIES_FAILED = "GET_APP_SPECIALTIES_FAILED"
