export const GET_USER_NOTIFICATIONS_REQUEST = "GET_USER_NOTIFICATIONS_REQUEST";
export const GET_USER_NOTIFICATIONS_SUCCESS = "GET_USER_NOTIFICATIONS_SUCCESS";
export const GET_USER_NOTIFICATIONS_FAILED = "GET_USER_NOTIFICATIONS_FAILED";
export const SAVE_SOCKET_NOTIFICATION = "SAVE_SOCKET_NOTIFICATION";
export const MARK_ALL_AS_READED = "MARK_ALL_AS_READED";
