export const HOME_ROUTE = "HOME_ROUTE";

export const HOME_SCREEN = "Home";
export const FAQ_SCREEN = "FAQ";
export const NOTIFICATIONS_SCREEN = "NOTIFICATIONS_SCREEN";
export const PHONE_CONFIRMATION_SCREEN = "PHONE_CONFIRMATION_SCREEN";
export const MAKE_APPOINTMENT_SCREEN = "MAKE_APPOINTMENT_SCREEN";