export const GET_ALL_PRATICIENS = "GET_ALL_PRATICIENS";
export const GET_ALL_PRATICIENS_SUCCESS = "GET_ALL_PRATICIENS_SUCCESS";
export const GET_ALL_PRATICIENS_FAILED = "GET_ALL_PRATICIENS_FAILED";

export const SEARCH_PRAT_BY_KEY = "SEARCH_PRAT_BY_KEY";
export const SEARCH_PRAT_BY_KEY_SUCCESS = "SEARCH_PRAT_BY_KEY_SUCCESS";
export const SEARCH_PRAT_BY_KEY_FAILED = "SEARCH_PRAT_BY_KEY_FAILED";