export const REINITIALIZE = 'REINITIALIZE'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

export const REGISTER_USER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_USER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_USER_FAILED = 'REGISTER_FAILED';

export const LOCAL_AUTH_REQUEST = "LOCAL_AUTH_REQUEST";
export const LOCAL_AUTH_FAILED = "LOCAL_AUTH_FAILED";
export const LOCAL_AUTH_SUCCESS = "LOCAL_AUTH_SUCCESS";

export const UPDATE_USER_INFORMATION_SUCCESS = 'UPDATE_USER_INFORMATION_SUCCESS';
export const UPDATE_USER_INFORMATION_RESQUEST = 'UPDATE_USER_INFORMATION_RESQUEST';
export const UPDATE_USER_INFORMATION_FAILED = 'UPDATE_USER_INFORMATION_FAILED';

export const SEND_EXPO_TOKEN_REQUEST = "SEND_EXPO_TOKEN_REQUEST"
export const SEND_EXPO_TOKEN_SUCCESS = "SEND_EXPO_TOKEN_SUCCESS"
export const SEND_EXPO_TOKEN_FAILED = "SEND_EXPO_TOKEN_FAILED"

export const SET_USER_PROFIL_SUCCESS = 'SET_USER_PROFIL_SUCCESS';
export const SET_USER_PROFIL_RESQUEST = 'SET_USER_PROFIL_SUCCESS_RESQUEST';
export const SET_USER_PROFIL_SUCCESS_FAILED = 'SET_USER_PROFIL_SUCCESS_FAILED';

export const PROCESS_VERIF_CODE_REQUEST = "PROCESS_VERIF_CODE_REQUEST";
export const PROCESS_VERIF_CODE_SUCCESS = "PROCESS_VERIF_CODE_SUCCESS";
export const PROCESS_VERIF_CODE_FAILED = "PROCESS_VERIF_CODE_FAILED";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_REQUEST_SUCCESS = "RESET_PASSWORD_REQUEST_SUCCESS";
export const RESET_PASSWORD_REQUEST_FAILED = "RESET_PASSWORD_REQUEST_FAILED";

export const COORDS_TO_ADDRESS_REQUEST = "COORDS_TO_ADDRESS_REQUEST"
export const COORDS_TO_ADDRESS_FAILED = "COORDS_TO_ADDRESS_FAILED"
export const COORDS_TO_ADDRESS_SUCCESS = "COORDS_TO_ADDRESS_SUCCESS"

export const GET_MAP_DIRECTIONS_REQUEST = "GET_MAP_DIRECTIONS_REQUEST"
export const GET_MAP_DIRECTIONS_SUCCESS = "GET_MAP_DIRECTIONS_SUCCESS"
export const GET_MAP_DIRECTIONS_FAILED = "GET_MAP_DIRECTIONS_FAILED"

export const SAVE_CLIENT_ID = "SAVE_CLIENT_ID"
