export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const REGISTER_USER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_USER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_USER_FAILED = 'REGISTER_FAILED';