export const REINITIALIZE = 'REINITIALIZE'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

export const REGISTER_USER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_USER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_USER_FAILED = 'REGISTER_FAILED';

export const LOCAL_AUTH_REQUEST = "LOCAL_AUTH_REQUEST";
export const LOCAL_AUTH_FAILED = "LOCAL_AUTH_FAILED";
export const LOCAL_AUTH_SUCCESS = "LOCAL_AUTH_SUCCESS";

export const UPDATE_USER_INFORMATION_SUCCESS = 'UPDATE_USER_INFORMATION_SUCCESS';
export const UPDATE_USER_INFORMATION_RESQUEST = 'UPDATE_USER_INFORMATION_RESQUEST';
export const UPDATE_USER_INFORMATION_FAILED = 'UPDATE_USER_INFORMATION_FAILED';

export const PROCESS_VERIF_CODE_REQUEST = "PROCESS_VERIF_CODE_REQUEST";
export const PROCESS_VERIF_CODE_SUCCESS = "PROCESS_VERIF_CODE_SUCCESS";
export const PROCESS_VERIF_CODE_FAILED = "PROCESS_VERIF_CODE_FAILED";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_REQUEST_SUCCESS = "RESET_PASSWORD_REQUEST_SUCCESS";
export const RESET_PASSWORD_REQUEST_FAILED = "RESET_PASSWORD_REQUEST_FAILED";