export const SET_FORM_RDV = 'SET_FORM_RDV';
export const SET_RDV_DURATION = 'SET_RDV_DURATION';

export const GET_MOTIFS_REQUEST = "GET_MOTIFS_REQUEST"
export const GET_MOTIFS_REQUEST_FAILED = "GET_MOTIFS_REQUEST_FAILED"
export const GET_SPECIALITIES_REQUEST = "GET_SPECIALITIES_REQUEST"
export const GET_MOTIFS_REQUEST_SUCCESS = "GET_MOTIFS_REQUEST_SUCCESS"
export const GET_SPECIALITIES_REQUEST_FAILED = "GET_SPECIALITIES_REQUEST_FAILED"
export const GET_SPECIALITIES_REQUEST_SUCCESS = "GET_SPECIALITIES_REQUEST_SUCCESS"

export const GET_CLINIQUES_REQUEST = "GET_CLINIQUES_REQUEST"
export const GET_CLINIQUE_REQUEST_FAILED = "GET_CLINIQUE_REQUEST_FAILED"
export const GET_CLINIQUE_REQUEST_SUCCESS = "GET_CLINIQUE_REQUEST_SUCCESS"

export const GET_PRATICIENS_REQUEST = "GET_PRATICIENS_REQUEST"
export const GET_PRATICIENS_REQUEST_FAILED = "GET_PRATICIENS_REQUEST_FAILED"
export const GET_PRATICIENS_REQUEST_SUCCESS = "GET_PRATICIENS_REQUEST_SUCCESS"

export const GET_DISPO_REQUEST = "GET_DISPO_REQUEST"
export const GET_DISPO_REQUEST_FAILED = "GET_DISPO_REQUEST_FAILED"
export const GET_DISPO_REQUEST_SUCCESS = "GET_DISPO_REQUEST_SUCCESS"

export const POST_RDV_REQUEST = "POST_RDV_REQUEST"
export const POST_RDV_REQUEST_SUCCESS = "POST_RDV_REQUEST_SUCCESS"
export const POST_RDV_REQUEST_FAILED = "POST_RDV_REQUEST_FAILED"


export const CLEAR_ERR_SUCC = 'CLEAR_ERR_SUCC'
export const GET_ALL_MY_RDV = 'GET_ALL_MY_RDV'
export const GET_ALL_MY_RDV_SUCCESS = 'GET_ALL_MY_RDV_SUCCESS'
export const GET_ALL_MY_RDV_FAILED = 'GET_ALL_MY_RDV_FAILED'


export const PUT_RDV_REQUEST = "PUT_RDV_REQUEST"
export const PUT_RDV_REQUEST_SUCCESS = "PUT_RDV_REQUEST_SUCCESS"
export const PUT_RDV_REQUEST_FAILED = "PUT_RDV_REQUEST_FAILED"

export const CANCEL_RDV_REQUEST = "CANCEL_RDV_REQUEST"
export const CANCEL_RDV_REQUEST_SUCCESS = "CANCEL_RDV_REQUEST_SUCCESS"
export const CANCEL_RDV_REQUEST_FAILED = "CANCEL_RDV_REQUEST_FAILED"

export const GET_CLINIC_OF_SPEC_PRAT = "GET_CLINIC_OF_SPEC_PRAT"
export const GET_CLINIC_OF_SPEC_PRAT_SUCCESS = "GET_CLINIC_OF_SPEC_PRAT_SUCCESS"
export const GET_CLINIC_OF_SPEC_PRAT_FAILED = "GET_CLINIC_OF_SPEC_PRAT_FAILED"

export const GET_SINGLE_PRAT_SUCCESS = "GET_SINGLE_PRAT_SUCCESS"

export const SAVE_EXTERNAL_PR_DATA = "SAVE_EXTERNAL_PR_DATA"